---
- name: Deploy Rest War
  hosts: '{{ host }}'
  become: yes
 
  vars:
    rest_version:
    tomcat_path: "/home/clix_user/apache-tomcat-7.0.82"
    bkp_path: "/home/clix_user/backup/website"
    replace_config: false
    config_version: "0.0.1"
    repo_type: "SNAPSHOT"
    
  tasks:
  - debug: msg="Host is {{ ansible_fqdn }}"
  
  - shell : date '+%Y%m%d%H%M%S'
    register: datetime_output
    
  - name: stop tomcat7 service
    command: "nohup {{ tomcat_path }}/bin/shutdown.sh"
 
  - name: Check if clix-cms-rest.war file exists
    stat:
      path: "{{ tomcat_path }}/webapps/clix-cms-rest.war"
    register: war
    
  - name: Create Folder
    file: 
      path: "{{ bkp_path }}/Bkp-{{ rest_version }}-{{ datetime_output.stdout }}"
      state: directory
    when: war.stat.exists == true
  
  - name: Backup old clix-cms-rest war file if exist
    command: mv "{{ tomcat_path }}/webapps/clix-cms-rest.war" "{{ bkp_path }}/Bkp-{{ rest_version }}-{{ datetime_output.stdout }}/clix-cms-rest.war"
    when: war.stat.exists == true
    
  - name: Delete old clix-cms-rest.war file from webapps
    file:
      path: "{{ tomcat_path }}/webapps/clix-cms-rest.war"
      state: absent
      
  - name: Delete old clix-cms-rest folder from webapps
    file:
      path: "{{ tomcat_path }}/webapps/clix-cms-rest"
      state: absent
      
  - name: Download war file
    command: wget --no-check-certificate "http://10.106.3.21:8081/repository/cms-{{ repo_type }}/com/clix/cms/clix-cms-rest/{{ rest_version }}/clix-cms-rest-{{ rest_version }}.war" -O "{{ tomcat_path }}/webapps/clix-cms-rest.war" -k
  
  - name: Change access permission of rest war file
    file:
      path: "{{ tomcat_path }}/webapps/clix-cms-rest.war"
      mode: 755
      
  - name: Check if clix_cms_config.properties file exists
    stat:
      path: "{{ tomcat_path }}/conf/clix_cms_config.properties"
    register: config
  
  - name: Create Folder
    file: 
      path: "{{ bkp_path }}/Bkp-{{ rest_version }}-{{ datetime_output.stdout }}/conf"
      state: directory
    when: 
      - config.stat.exists == true
      - replace_config
    
  - name: Backup old clix_cms_config.properties file if exist
    command: mv "{{ tomcat_path }}/conf/clix_cms_config.properties" "{{ bkp_path }}/Bkp-{{ rest_version }}-{{ datetime_output.stdout }}/conf/clix_cms_config.properties"
    when: 
      - config.stat.exists == true
      - replace_config
    
  - name: Download and replace config file
    command: wget --no-check-certificate "http://10.106.3.21:8081/repository/cms-RELEASE/com/clix/cms/clix_cms_config/{{ config_version }}/clix_cms_config-{{ config_version }}.properties" -O "{{ tomcat_path }}/conf/clix_cms_config.properties" -k
    when: 
      - replace_config
      
  - name: start tomcat7 service
    command: "nohup {{ tomcat_path }}/bin/startup.sh"
  
  - name: sleep for 10 seconds and continue with play
    wait_for: timeout=10
    
  - shell : ps -ef | awk '/[t]omcat/{print $2}'
    register: tomcat_pid
  
  - debug: msg="Tomcat is running with PID {{tomcat_pid.stdout}}"
    when: tomcat_pid.stdout != ""
