---
- name: Deploy Web
  hosts: hippo_dev
  become: yes
 
  vars:
    web_version:
    tomcat_path:
    bkp_path:
    repo_type:
    
  tasks:
  - shell : date '+%Y%m%d%H%M%S'
    register: datetime_output
    
  - name: stop tomcat7 service
    command: "nohup {{ tomcat_path }}/bin/shutdown.sh"
    
  - name: Check if cms.war file exists
    stat:
      path: "{{ tomcat_path }}/webapps/cms.war"
    register: cmswar
	
  - name: Check if site.war file exists
    stat:
      path: "{{ tomcat_path }}/webapps/site.war"
    register: sitewar
    
  - name: Create Folder
    file: 
      path: "{{ bkp_path }}/Bkp-{{ web_version }}-{{ datetime_output.stdout }}"
      state: directory
    when: cmswar.stat.exists == true or sitewar.stat.exists == true
  
  - name: Backup old cms war file if exist
    command: mv "{{ tomcat_path }}/webapps/cms.war" "{{ bkp_path }}/Bkp-{{ web_version }}-{{ datetime_output.stdout }}/cms.war"
    when: cmswar.stat.exists == true
  
  - name: Backup old site war file if exist
    command: mv "{{ tomcat_path }}/webapps/site.war" "{{ bkp_path }}/Bkp-{{ web_version }}-{{ datetime_output.stdout }}/site.war"
    when: sitewar.stat.exists == true
    
  - name: Delete old cms.war file from webapps
    file:
      path: "{{ tomcat_path }}/webapps/cms.war"
      state: absent
      
  - name: Delete old cms folder from webapps
    file:
      path: "{{ tomcat_path }}/webapps/cms"
      state: absent
	  
  - name: Delete old site.war file from webapps
    file:
      path: "{{ tomcat_path }}/webapps/site.war"
      state: absent
      
  - name: Delete old site folder from webapps
    file:
      path: "{{ tomcat_path }}/webapps/site"
      state: absent

  - name: Download tar file
    command: wget --no-check-certificate "http://10.106.3.21:8081/repository/cms-{{ repo_type }}/com/clix/cms/web/{{ web_version }}/web-{{ web_version }}.tar.gz" -O "{{ tomcat_path }}/web.tar.gz" -k
  
  - name: Change access permission of web tar file
    file:
      path: "{{ tomcat_path }}/web.tar.gz"
      mode: 755
  
  - name: Extract tar file
    command: tar -xvf "{{ tomcat_path }}/web.tar.gz"
      
  - name: start tomcat7 service
    command: "nohup {{ tomcat_path }}/bin/startup.sh"
  
  - name: sleep for 60 seconds and continue with play
    wait_for: timeout=60
    
  - shell : ps -ef | awk '/[t]omcat/{print $2}'
    register: tomcat_pid
  
  - debug: msg="Tomcat is running with PID {{tomcat_pid.stdout}}"
    when: tomcat_pid.stdout != ""
