---
- name: Deploy Rest War
  hosts: 192.168.33.50
  become: true
  vars:
    rest_version: 0.0.1-SNAPSHOT
    time: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S')}}"
  tasks:    
  - name: Create Folder
    file: 
      path: /tmp/Bkp-{{ rest_version }}-{{ time }}
      state: directory
