---
- name: Deploy Rest War
  hosts: 192.168.33.50
  become: true
  vars:
    rest_version: 
    time: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
  tasks:    
  - name: Delete old clix-cms-rest folder from webapps
    file:
      path: /opt/tomcat/apache-tomcat/webapps/clix-cms-rest
      state: absent
      
  - name: Create Folder
    file: 
      path: /tmp/Bkp-{{ rest_version }}-{{ time }}
      state: directory
