---
- name: Deploy Rest War
  hosts: 192.168.33.50
  
  vars:
    rest_version: 
    time: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
    
  tasks:
  - name: Shutdown Tomcat
    command: ./shutdown.sh
    args:
      chdir: /opt/tomcat/apache-tomcat/bin
      
  - name: Create Folder
    file: 
      path: /tmp/Bkp-{{ rest_version }}-{{ time }}
      state: directory
 
  - name: Backup old clix-cms-rest war file
    copy: 
    src: /opt/tomcat/apache-tomcat/webapps/clix-cms-rest.war
    dest: /tmp/Bkp-{{ rest_version }}-{{ time }}/clix-cms-rest.war
    failed_when: false
    
  - name: Delete old clix-cms-rest.war file from webapps
    file:
      path: /opt/tomcat/apache-tomcat/webapps/clix-cms-rest.war
      state: absent
      
  - name: Delete old clix-cms-rest folder from webapps
    file:
      path: /opt/tomcat/apache-tomcat/webapps/clix-cms-rest
      state: absent
      
  - name: Download war file
    command: wget --no-check-certificate "http://10.106.3.21:8081/repository/cms-SNAPSHOT/com/clix/cms/clix-cms-rest/{{ rest_version }}/clix-cms-rest-{{ rest_version }}.war" -O /opt/tomcat/apache-tomcat/webapps/clix-cms-rest.war -k
    
  - name: Start Tomcat
    command: ./startup.sh
    args:
      chdir: /opt/tomcat/apache-tomcat/bin
