---
- name: Deploy Rest War
  hosts: '{{ host }}'
  become: yes
 
  vars:
    tomcat_path: "/home/clix_user/apache-tomcat-7.0.82"
    bkp_path: "/home/clix_user/backup/website"
        
  tasks:
  - debug: msg="Host is {{ play_hosts }}"
    
  - name: get the username running the deploy
    local_action: command whoami
    register: username_on_the_host

  - name: Check if tomcat folder/path exists
    stat:
      path: "{{ tomcat_path }}"
    register: tomcat_path_out
    
  - fail: msg="Tomcat path {{ tomcat_path }} is invalid. Please provide correct path with tomcat_path parameter"
    when: tomcat_path_out.stat.exists == false
  
  - fail: msg="{{ username_on_the_host.stdout }} doesnot have write access to {{ tomcat_path }} folder"
    when: tomcat_path_out.stat.wusr == false
    
  - name: Check if backup folder/path exists
    stat:
      path: "{{ bkp_path }}"
    register: bkp_path_out
  
  - fail: msg="Backup path {{ bkp_path }} is invalid. Please provide correct path with bkp_path parameter"
    when: bkp_path_out.stat.exists == false
    
  - fail: msg="username_on_the_host.stdout doesnot have write access to {{ bkp_path }} folder"
    when: bkp_path_out.stat.wusr == false
    
  - name: Check if clix-cms-rest.war file exists
    stat:
      path: "{{ tomcat_path }}/webapps/clix-cms-rest.war"
    register: war
  
  - fail: msg="{{ username_on_the_host.stdout }} user doen't have permission to delete clix-cms-rest.war file"
    when: 
      - war.stat.pw_name != 'root'
      - war.stat.exists == true
    
  - name: Check if clix-cms-rest folder exists
    stat:
      path: "{{ tomcat_path }}/webapps/clix-cms-rest"
    register: f_rest
  
  - fail: msg="{{ username_on_the_host.stdout }} user doen't have permission to delete on clix-cms-rest folder"
    when: 
      - f_rest.stat.pw_name != 'root'
      - f_rest.stat.exists == true
  
  - name: Check if webapps folder permission
    stat:
      path: "{{ tomcat_path }}/webapps"
    register: tomcat_webapps
    
  - fail: msg="{{ username_on_the_host.stdout }} doesnot have write access to {{ tomcat_path }}/webapps folder"
    when: 
      - tomcat_webapps.stat.wusr == false
      - tomcat_webapps.stat.exists == true
        
  - name: Check if clix_cms_config.properties file exists
    stat:
      path: "{{ tomcat_path }}/conf/clix_cms_config.properties"
    register: config
 
  - fail: msg="{{ username_on_the_host.stdout }} doesnot have replace/write access to {{ tomcat_path }}/conf/clix_cms_config.properties file"
    when: 
      - config.stat.exists == true
      - config.stat.pw_name != 'root'
