---
- name: Deploy Rest War
  hosts: 192.168.33.50
  become: true
  vars:
    rest_version: 

  tasks:
  - name: Shutdown Tomcat
    command: ./shutdown.sh
    args:
      chdir: /home/vagrant/apache-tomcat-7.0.90/bin
      
  - name: Delete old clix-cms-rest folder from webapps
    file:
      path: /home/vagrant/apache-tomcat-7.0.90/clix-cms-rest
      state: absent
      
  - name: Create Folder
    file: 
      path: /tmp/"{{ rest_version }}"
      state: directory
      
  - name: Backup old clix-cms-rest war file
    command: mv clix-cms-rest /tmp/"{{ rest_version }}"
    args:
      chdir:/home/vagrant/apache-tomcat-7.0.90/webapps
      
  - name: Download war file
    command: wget <link>
    args:
      chdir:/home/vagrant/apache-tomcat-7.0.90/webapps
      
  - name: Rename war file
    command: mv clix-cms-rest-"{{ rest_version }}".war clix-cms-rest.war
    args:
      chdir:/home/vagrant/apache-tomcat-7.0.90/webapps
      
  - name: Start Tomcat
    command: ./startup.sh
    args:
      chdir: /home/vagrant/apache-tomcat-7.0.90/bin
