---
- name: Deploy Rest War
  hosts: 192.168.33.50
  become: true

  tasks:
  - name: Shutdown Tomcat server
  command: ./shutdown.sh
  args:
    chdir: /home/vagrant/apache-tomcat-7.0.90/bin
    
  - name: Start Tomcat
    command: ./startup.sh
  args:
    chdir: /home/vagrant/apache-tomcat-7.0.90/bin
