---
- name: Deploy Rest War
  hosts: 192.168.33.50
  become: true

  tasks:
  - name: Shutdown Tomcat
    command: ./shutdown.sh
    args:
      chdir: /home/vagrant/apache-tomcat-7.0.90/bin
      
  - name: Delete old clix-cms-rest folder from webapps
    file:
      path: /home/vagrant/apache-tomcat-7.0.90/clix-cms-rest
      state: absent
      
  - name: Backup old clix-cms-rest war file
  
  - name: Download war file
    command: wget <link>
    args:
      chdir:/home/vagrant/apache-tomcat-7.0.90/webapps
      
  - name: Shutdown Tomcat
    command: ./shutdown.sh
    args:
      chdir: /home/vagrant/apache-tomcat-7.0.90/bin
    
  - name: Start Tomcat
    command: ./startup.sh
    args:
      chdir: /home/vagrant/apache-tomcat-7.0.90/bin
